### ISSUE TITLE
파워링크 호출 값 설정 문의

### ISSUE THREAD

**Issue by hyungyoung123** [naver/glad-sdk-web#2]
파워링크 JS 연동에서 test / mock 값 설정 문의입니다.

  - 정의 
test (type: boolean; default: false): 광고 노출 시스템 sandbox 환경 (test 환경)으로 연결한다. Production 환경 채널 정보가 아닌 test 환경 채널 정보와 연결되기 때문에 production 환경 채널 등록 이전에 연동 개발 시 활용할 수 있다.
mock (type: boolean; default: false): 광고 노출 시스템 mock API로 연결한다. response object 내 광고 노출 시스템이 제공하는 모든 properties가 포함되기 때문에 연동 개발 시 활용할 수 있다.
  - 질문 사항 : test / mock 값을 sandbox와 상용에서의 설정값을 문의드립니다. 아래의 sample처럼 하면 되는지요?
     o 개발환경
         test : true
         mock : true
     o 상용환경
         test : false
         mock : false

감사합니다.

**Comment by phenix4u** [comment]
안녕하세요. 네이버 박종국입니다.

죄송하지만 혹시 저희 GLAD SDK 가이드(https://naver.github.io/glad-sdk-guide/web_new/common/get_started/) 를 통해 
광고 적용하신게 맞는지 궁금합니다. 문의주신 파워링크 JS 관련 내용이 저희쪽에서 제공하는 라이브러리가 아닌 것으로 보이는데요.

관런 서비스 페이지 URL을 공유주시면 저희 SDK 로딩 여부를 확인 가능할것 같습니다. 혹시라도 저희 쪽에서 제공하는 라이브러리가 아니라면 
파워링크 담당 부서쪽으로 다시 문의주셔야 될 것으로 보입니다.


감사합니다.
