### ISSUE TITLE
광고 배너 클릭시 기본 동작 disable 및 이동 타겟 정보 문의

### ISSUE THREAD

**Issue by piohan83** [naver/glad-sdk-web#3]
안녕하세요 GLAD SDK 적용중에 문의드립니다 

적용업체: TMAP 
필요사항:
1. 광고 배너 클릭시 기본 클릭 동작 disable
현재 저희는 앱 내의 웹뷰 형태의 페이지로 적용중이며 배너 클릭시 자동으로 동작하는것이 아니라 직접 앱내 스킴을 이용하여야 하는데 현재는 iframe 안에서 기본으로 click 동작이 실행되고 있습니다. 이를 막을 수 있는 옵션이 있는지 궁금합니다

2. 광고 배너 클릭시 이동해야할 목적지 정보
click 이벤트를 받아보면 slot내 함수들을 통해서는 실제 타겟 url을 알 수가 없는데 해당 방법이 있는지 문의드립니다 
(setNativeClickHandler 을 넣으면 첫번째 파라미터로 받아 볼 수 있는데 이를 사용해도 되는건지도 궁금합니다. 1번의 기본동작 막는 기능이 동작한다면 이것으로 가능해 보이네요)

3. (추가) 광고 배너 사이즈 문의
현재 적용해 본 결과 iframe 내 제한으로 234\*50 사이즈가 고정되는데 저희가 할당받은 사이즈는 320\*50 사이즈입니다
광고별로 최대값이 너비 320이라고 하면 234너비는 가운데 정렬 하면 되므로 문제가 안되지만 
저희 서비스 화면노출시에 높이를 56으로 맞추고 있어서 이부분은 하단 여백이 생기게 되는데요. 해당 사이즈 조절을 할 수 있는지 문의드립니다

![image](https://user-images.githubusercontent.com/807184/173298692-0891cf31-ddf1-4e47-9dd2-52a03afd0f6f.png)

**Comment by ho-jin-lee** [comment]
안녕하세요, GFP SDK Dev 이호진입니다.

1번과 2번 문의에 대해서, 2번 문의사항에 언급해주신것 처럼 `setNativeClickHandler` API를 사용하시면 됩니다.

커스텀 클릭 핸들러 적용 시, SDK의 기본 click 랜딩은 동작하지 않습니다.

- [setNativeClickHandler](https://naver.github.io/glad-sdk-guide/ko/web_new/common/additional_api/#네이티브-광고-클릭-핸들러-등록네이티브-전용)

  ```js
  adSlot.setNativeClickHandler(function (curl, furl) {
    // curl : click url(string), furl: fallback url(string)
    // click 발생시 동작 명시
  });
  ```

3번 문의에 대해서, 해당 광고 마크업이 높이가 50으로 고정되는 스펙으로 개발되어서 높이 조절은 불가능합니다.

감사합니다.

**Comment by piohan83** [comment]
@ho-jin-lee 님 확인 감사드립니다 

setNativeClickHandler 는 제가 실행 위치를 잘못 잡았었네요 
테스트 하기 위해 이벤트 콜백에 오는 adInfo에서 slot을 이용해서만 등록했는데 그래서 안되는거였습니다

findAdSlot으로 직접 가져와서 등록하니 정상적으로 기본 클릭이 막히는것 확인했습니다

높이의 여백은 저희쪽에서 우선 맞춰보도록 하겠습니다 감사합니다
