### ISSUE TITLE
광고 랜딩 이슈 확인 요청 드립니다. 

### ISSUE THREAD

**Issue by smartkgh** [naver/glad-sdk-web#5]
광고 랜딩시  <a  href="..."   target="_blank" > 로 랜딩 시   모웹 SDK 에서  external browser 으로 랜딩 할 수 있는지 문의 드립니다.
해당 서비스 App 에서는  멀티윈도우 지원이 되지 않습니다. (setSupportMultipleWindows(false) ) 
확인 부탁 드립니다.

**Comment by sungwook-kwon** [comment]
@smartkgh 

안녕하세요. 네이버 권성욱입니다.
비슷한 내용이 있어서 아래 링크 참고 부탁드립니다.

https://github.com/naver/glad-sdk-web/issues/4#issuecomment-1172111190

위 클릭 랜딩 관련하여 추가 확인이 필요하신 경우 코멘트 남겨주시면 확인 후 답변 드리겠습니다.
