### ISSUE TITLE
맞춤형 광고 i마크 클릭 시, 안내 페이지로 이동되지 않는 이슈

### ISSUE THREAD

**Issue by NAM-Ad** [naver/glad-sdk-web#8]
@hyungyoung123 님, 안녕하세요. 

Syrup iOS 앱 (Web SDK 적용지면) 에서 소재 우측 상단에 `i마크  클릭 > 이 광고가 보이는 이유`를 클릭할 경우,  
**맞춤형 광고 안내 페이지가 아닌 광고 영역이 보여지는 현상**이 확인되고 있습니다. 

재현예시는 아래 참고 부탁드리며,
혹시 SKP 측에서 수정 필요한 내용 있을지 확인 부탁드리겠습니다. 

참고로 `이 광고가 보이는 이유`를 클릭할 경우, 아래와 같이 맞춤형 광고 안내 페이지로 이동되어야 합니다. 
> ![image](https://user-images.githubusercontent.com/109189952/185543834-a13b50ca-5b7b-4935-82c7-37094d56a57e.png)

**<참고>**
- 맞춤형 광고일 경우, 소재 우측 상단에 i마크가 노출되고, 그 외의 경우엔 동일 위치에 AD마크가 노출됩니다. 

---- 

## 재현예시

https://user-images.githubusercontent.com/109189952/185543379-2207adc3-2f6d-419d-b11d-9b0402ce799d.mp4

**Comment by NAM-Ad** [comment]
참조자 확대차 공유드립니다. 
혹시 저희 쪽에서 추가로 확인드릴 부분 있으면 말씀 부탁드리겠습니다. 

/cc @changhoh0708

**Comment by hyungyoung123** [comment]
> 참조자 확대차 공유드립니다. 혹시 저희 쪽에서 추가로 확인드릴 부분 있으면 말씀 부탁드리겠습니다.
> 
> /cc @changhoh0708

점검해 보고 의견을 드리겠습니다.

**Comment by youngman71** [comment]
@NAM-Ad 님,
위 내용 관련하여
1. Syrup iOS에서만 발생되는 건지요?
2. Syrup 3개 인벤토리 모두 해당되는지요?
3. 가이드 어느 부분을 참조하면 되는지요?

**Comment by sungwook-kwon** [comment]
@youngman71 님 안녕하세요.

iOS 에서만 재현되고 있으며, 전체 영역에서 확인하지 못했으나 동일하게 재현될 것으로 생각하고 있습니다.

참고로 광고 SDK 내부에서 **이 광고가 보이는 이유** 버튼 클릭시 `window.open` mehtod 를 이용하여 새창을 띄우고 있는데요.
혹시 window.open 에 대해 재정의 하여 사용하고 계신지 확인 부탁드립니다.

**Comment by sungwook-kwon** [comment]
@youngman71 님 안녕하세요.

window.open 에 대한 재정의 여부에 대해서 확인 부탁드립니다.

이와 별개로,
광고영역에 clickHandler 사용시
`맞춤형 안내 페이지` 랜딩도 clickHandler 로 처리되도록 수정하여 **9/1(목)** 배포 예정입니다.
시럽에서 clickHandler 를 사용중이신 걸로 보여서 SDK 배포 되면 문의주신 부분은 해결 될 것으로 보입니다.

감사합니다.

**Comment by sungwook-kwon** [comment]
@youngman71 님. 안녕하세요.

금일 14시07분 맞춤형 안내 페이지 랜딩에 clickHandler 적용된 SDK 배포 하였으며
safari 랜딩 확인 되었습니다.

감사합니다.
